---
title: Title
subtitle: Subtitle
author: First Last
date: last-modified
date-format: "[Updated:] D MMM, YYYY"
format:
  id-html: default
  id-pdf: default
  id-docx: default
---


```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)


library(tidyverse)
library(data.table)
library(gtsummary)
library(cowplot)
library(flextable)
library(patchwork)
library(idstyle)
library(idtools)
library(showtext)

knitr::opts_chunk$set(fig.width=6, fig.height=3.5, out.width = '100%',
                      fig.showtext = TRUE)

# Get Tables
# tab_use <- pull_tables()

# Get Figures
# fig_use <- pull_figures()
```


<!-- Note: start at h2 level, h1 reserved for title -->
## Methods


## Results 


## Discussion


## References



### Tables

Flextable formatting:

 - Black & white (default)

```{r}

head(mtcars) |> format_flex_table() 
```

 - "wake" color
 
```{r}
head(mtcars) |> format_flex_table(color = 'wake') 
```

### Plots


 - ID color palette for factors

```{r}
ggplot(mtcars) + geom_bar(aes(x = carb, fill = factor(carb)))
```

 - Label formatting
 
```{r}
gg2 <- mtcars |> ggplot(aes(x = mpg, y = hp, color = cut(mtcars$hp,6))) + #discrete scale
  geom_point() + labs(title = 'This is a title for my graph',
                      subtitle = 'This is a subtitle for my graph',
                      caption = 'This is a caption for my graph',
                      color = 'HP')
gg2
```

 - Grids
 
```{r}
gg2 + theme_id(grid = 'both') +
  labs(title = 'Now with grids!')
```

 - Facets

```{r}
gg2 + facet_wrap(~gear) + theme_id_facet(grid = 'y') +
  labs(title = 'Some facets! And y grids only')

```

 - Interactive

```{r eval=knitr::is_html_output()}

plotly::ggplotly(gg2)

```



 - Theme Updating (ggplot2 default)


```{r}

theme_set_gg()
ggplot(mtcars) + geom_bar(aes(x = carb, fill = factor(carb)))

```

 - Theme Updating (Atrium default)

```{r}

theme_set_atrium()
ggplot(mtcars) + geom_bar(aes(x = carb, fill = factor(carb)))

theme_set_wake() #and back to wake for future graphics

```
 
 - Font Awesome
 
```{r}

mtcars |> ggplot(aes(x = mpg, y = hp)) +
  geom_fontawesome('head-side-virus', size = 10) +
  labs(title = 'Using font awesome icons')
```


