---
title: This is My Title
subtitle: This is My Subtitle
author: First Last
date: last-modified
date-format: "[Updated:] D MMM, YYYY"
format:
  idreport-html: default
  idreport-pdf: default
  idreport-docx: default
---


```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
#                       fig.height = 10, fig.width = 14)
library(tidyverse)
library(data.table)
library(gtsummary)
library(cowplot)
library(flextable)
library(patchwork)
library(idstyle)

gtsummary::theme_gtsummary_journal("jama", set_theme = TRUE)
hh <- here::here
theme_set(cowplot::theme_cowplot())
# Get Tables
# tab_use <- pull_tables()

# Get Figures
# fig_use <- pull_figures()
```


<!-- Note: start at h2 level, h1 reserved for title -->
## Methods


## Results 


###  Default Print

```{r}
head(mtcars) #default print method
```

### ID flextable

```{r}

head(mtcars) |> format_flex_table() #idstyle flextable
```






## Discussion



## References

[a link](https://www.google.com)
